# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/catppuccin_frappe.toml"]

[font]
size = 14

[font.normal]
family = "0xProto Nerd Font"

[ env ]
TERM = "xterm-256color"

[shell]
program = "/bin/bash"

[window]
padding.x = 10
padding.y = 10
#startup_mode = "Maximized"  # Options: "Windowed", "Maximized", "Fullscreen"
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

