# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"]

[shell]
program = "/bin/bash"

[font]
size = 14

[font.normal]
family = "0xProtoNerdFont"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
